export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const SET_LAY_DANH_SẠCH_NGUOI_DUNG = "SET_LAY_DANH_SẠCH_NGUOI_DUNG";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const SET_MA_LOAI_NGUOI_DUNG = "SET_MA_LOAI_NGUOI_DUNG"
export const SET_THONG_TIN_TIM_KIEM  = "SET_THONG_TIN_TIM_KIEM"